### ISSUE TITLE
Incorrect highlighting for 'substring'

### ISSUE THREAD

**Issue by dylansteele8** [mahmoudalismail/SublimeC0#3]
Created a variable called 'substring' and the 'string' portion of it was highlighted in yellow. I think that it shouldn't be highlighted since it is a part of a name and not the standalone type.

**Comment by mahmoudalismail** [comment]
Thank you for noting this issue. I will be rolling an update to the package, soon, and I will certainly fix this issue!

**Comment by mahmoudalismail** [comment]
I have just rolled an update (merged a pull request from Ben) and fixed the issue. Thank you again for pointing out issue. Please let me know if you face any issues in the future.
